[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
name = "client-storage-rs"
version = "0.1.0"

[dependencies]
core-foundation = "0.6.4"
euclid = "0.19.5"
gleam = "0.6.8"
glutin = "0.10.0"
libc = "0.2.32"
png = "0.14.0"
